//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNOW_Reporting_Test.ServiceNowReporting {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationItemViewModel", Namespace="http://schemas.datacontract.org/2004/07/DATG.SN.Common.SNOW")]
    [System.SerializableAttribute()]
    public partial class ConfigurationItemViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessCriticalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExecutiveOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SNOW_Reporting_Test.ServiceNowReporting.KeyValueString[] InterfacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupportGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupportGroup2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupportGroup3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SysIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shortNameMarkerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessCriticality {
            get {
                return this.BusinessCriticalityField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessCriticalityField, value) != true)) {
                    this.BusinessCriticalityField = value;
                    this.RaisePropertyChanged("BusinessCriticality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExecutiveOwner {
            get {
                return this.ExecutiveOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutiveOwnerField, value) != true)) {
                    this.ExecutiveOwnerField = value;
                    this.RaisePropertyChanged("ExecutiveOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITOwner {
            get {
                return this.ITOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.ITOwnerField, value) != true)) {
                    this.ITOwnerField = value;
                    this.RaisePropertyChanged("ITOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SNOW_Reporting_Test.ServiceNowReporting.KeyValueString[] Interfaces {
            get {
                return this.InterfacesField;
            }
            set {
                if ((object.ReferenceEquals(this.InterfacesField, value) != true)) {
                    this.InterfacesField = value;
                    this.RaisePropertyChanged("Interfaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAlias {
            get {
                return this.IsAliasField;
            }
            set {
                if ((this.IsAliasField.Equals(value) != true)) {
                    this.IsAliasField = value;
                    this.RaisePropertyChanged("IsAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportGroup {
            get {
                return this.SupportGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportGroupField, value) != true)) {
                    this.SupportGroupField = value;
                    this.RaisePropertyChanged("SupportGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportGroup2 {
            get {
                return this.SupportGroup2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SupportGroup2Field, value) != true)) {
                    this.SupportGroup2Field = value;
                    this.RaisePropertyChanged("SupportGroup2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportGroup3 {
            get {
                return this.SupportGroup3Field;
            }
            set {
                if ((object.ReferenceEquals(this.SupportGroup3Field, value) != true)) {
                    this.SupportGroup3Field = value;
                    this.RaisePropertyChanged("SupportGroup3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SysId {
            get {
                return this.SysIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SysIdField, value) != true)) {
                    this.SysIdField = value;
                    this.RaisePropertyChanged("SysId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tier {
            get {
                return this.TierField;
            }
            set {
                if ((object.ReferenceEquals(this.TierField, value) != true)) {
                    this.TierField = value;
                    this.RaisePropertyChanged("Tier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shortNameMarker {
            get {
                return this.shortNameMarkerField;
            }
            set {
                if ((object.ReferenceEquals(this.shortNameMarkerField, value) != true)) {
                    this.shortNameMarkerField = value;
                    this.RaisePropertyChanged("shortNameMarker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValueString", Namespace="http://schemas.datacontract.org/2004/07/DATG.SN.Common.Models")]
    [System.SerializableAttribute()]
    public partial class KeyValueString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string link {
            get {
                return this.linkField;
            }
            set {
                if ((object.ReferenceEquals(this.linkField, value) != true)) {
                    this.linkField = value;
                    this.RaisePropertyChanged("link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNowReporting.ISNOWReportingLibrary")]
    public interface ISNOWReportingLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNOWReportingLibrary/GetStatus", ReplyAction="http://tempuri.org/ISNOWReportingLibrary/GetStatusResponse")]
        string GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISNOWReportingLibrary/GetApplicationList", ReplyAction="http://tempuri.org/ISNOWReportingLibrary/GetApplicationListResponse")]
        SNOW_Reporting_Test.ServiceNowReporting.ConfigurationItemViewModel[] GetApplicationList(string BusinessID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISNOWReportingLibraryChannel : SNOW_Reporting_Test.ServiceNowReporting.ISNOWReportingLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SNOWReportingLibraryClient : System.ServiceModel.ClientBase<SNOW_Reporting_Test.ServiceNowReporting.ISNOWReportingLibrary>, SNOW_Reporting_Test.ServiceNowReporting.ISNOWReportingLibrary {
        
        public SNOWReportingLibraryClient() {
        }
        
        public SNOWReportingLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SNOWReportingLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SNOWReportingLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SNOWReportingLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public SNOW_Reporting_Test.ServiceNowReporting.ConfigurationItemViewModel[] GetApplicationList(string BusinessID) {
            return base.Channel.GetApplicationList(BusinessID);
        }
    }
}
